"""removed email column in student

Revision ID: c3d35db1d8ab
Revises: 418404624ede
Create Date: 2024-09-12 10:31:29.973399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d35db1d8ab'
down_revision: Union[str, None] = '418404624ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
